**References**: https://github.com/blockchain-etl/ethereum-etl

# Problem Set 1 Checklist

**Please customize the following inputs to generate your own results for discussion**

 
* Infura/Alchemy/QuickNode API endpoints: experiment with multiple node operators and see if you could get the same data

* Data radius, start, and end blocks: pick a smaller radius for testing before you scale

* Token address: Pick your choice of token in querying the token transfer part

**Please post the sharing (Allow viewing or commenting only) URL for your Google Colab after you are done below.**

Important: Change your private API token key to "API_KEY" before posting

## Question 1 
Did you get the same data querying via different node operators? Please point to at least one specific observation to validate your answer. 

Please insert Figures/Tables to better represent your idea.

Yes, I got the same data querying from Infura, Alchemy, and QuickNode.

**Infura data:**

|index|number|hash|parent\_hash|nonce|sha3\_uncles|logs\_bloom|transactions\_root|state\_root|receipts\_root|miner|difficulty|total\_difficulty|size|extra\_data|gas\_limit|gas\_used|timestamp|transaction\_count|base\_fee\_per\_gas|
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
|0|15537391|0x2f1dc309c7cc0a5a2e3b3dd9315fea0ffbc53c56f9237f3ca11b20de0232f153|0xd5b9efdd3659f5b635e0505d787d6b6cc3af4c660def9676188cda2bb026bffd|0xac2c3800025a764f|0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347|0x53a240c0610070015299420086041090205a1106210008400082344ac4142014222281180000001002893c01476030000a8481c92d142d00002000008a24281021504000002000bc6a0680081643112104010090090e265b3120540380000bc540600400c620108180042c5100cc08dc002a00904a51933160a81010444940f20000200423c83848130d8a0420c9c22240801a018108100a5222804b8d466b4b3a52014500a8a08424024c00241a80900a8041bc622db10209200022c04ca5000030000ec4110400248002300c40800148166384e7e80812920021018800e002007060c3004068125ac13058b160283604206948102888500600080058915c22|0xd976f002afbac9fdf1b028336719b602b9f4660ca103b8963b2f05a4f951cdc9|0xb8d426f8c8b6ae1c34f6bebf904971be1611c29e8889c7133bdef5e4e9e60b7f|0x6b4d994610806d8a5ed107996abc477688d4d0748763828f68c0d8df174ba256|0x829bd824b016326a401d083b33d092293333a830|11043900012338719|58749981610968571282265|47274|0xe4b883e5bda9e7a59ee4bb99e9b1bc4b2e22|30000000|16969164|1663224155|105|37949635702|
|1|15537392|0x2b3ea3cd4befcab070812443affb08bf17a91ce382c714a536ca3cacab82278b|0x2f1dc309c7cc0a5a2e3b3dd9315fea0ffbc53c56f9237f3ca11b20de0232f153|0x232b0043952c93d9|0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347|0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff|0x82864b3a65d1ac1917c426d48915dca0fc966fbf3f30fd051659f35dc3fd9be1|0xfee48a40a2765ab31fcd06ab6956341d13dc2c4b9762f2447aa425bb1c089b30|0x13c10513b52358022f800e2f9f1c50328798427b1b4a1ebbbd20b7417fb9719d|0xea674fdde714fd979de3edf0f56aa9716b898ec8|11049842297455506|58749992660810868737771|16568|0x617369612d65617374322d31763932|30000000|29990952|1663224156|61|38572377838|
|2|15537393|0x55b11b918355b1ef9c5db810302ebad0bf2544255b530cdce90674d5887bb286|0x2b3ea3cd4befcab070812443affb08bf17a91ce382c714a536ca3cacab82278b|0x62a3ee77461d4fc9|0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347|0x00000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000008000000000000000000000000000000000000000000000000020000000000000000000800000000004000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008400000000001002000000000000000000000000000000000002000000020000000020000000000000000000000000000000000000000040000000000000000000000000|0xdd5eec02b019ff76e359b09bfa19395a2a0e97bc01e70d8d5491e640167c96a8|0x4919dafa6ac8becfbbd0c2808f6c9511a057c21e42839caff5dfb6d3ef514951|0xbaa842cfd552321a9c2450576126311e071680a1258032219c6490b663c1dab8|0x829bd824b016326a401d083b33d092293333a830|11055787484078698|58750003716598352816469|1636|0xe4b883e5bda9e7a59ee4bb99e9b1bc460021|30000000|29991429|1663224162|1|43391016710|
|3|15537394|0x56a9bb0302da44b8c0b3df540781424684c3af04d0b7a38d72842b762076a664|0x55b11b918355b1ef9c5db810302ebad0bf2544255b530cdce90674d5887bb286|0x0000000000000000|0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347|0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff|0x1ea1746468686159ce730c1cc49a886721244e5d1fa9a06d6d4196b6f013c82c|0x40c07091e16263270f3579385090fea02dd5f061ba6750228fcc082ff762fda7|0x928073fb98ce316265ea35d95ab7e2e1206cecd85242eb841dbbcc4f568fca4b|0xeee27662c2b8eba3cd936a23f039f3189633e4c8|0|58750003716598352816469|18559|0x|30000000|29983006|1663224179|80|48811794595|
|4|15537395|0xe37e1a183a3d1c7234d090bfb7196081635919c26f2e65c67c106513158a7db4|0x56a9bb0302da44b8c0b3df540781424684c3af04d0b7a38d72842b762076a664|0x0000000000000000|0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347|0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff|0x5c56184fbce74e9c98d2a51aa2110963396047d84e8ce1ae1785337255cd11e0|0x2ca38a39c5517f658d107c19550334a9820a7393d14857f2c0e0458292668d64|0x1707e457973ce280debe93f5d478663d97ad192beea1f2fc65f391db80226e5e|0x0b3b161b8abeb6b04cb95c3e6047f80c120a0292|0|58750003716598352816469|36978|0x|30000000|29982083|1663224191|29|54906356355|

*Table 1. Copy of the output of datafram querying via Infura endpoint (15537391-15537395)*

**Alchemy data:**

|index|number|hash|parent\_hash|nonce|sha3\_uncles|logs\_bloom|transactions\_root|state\_root|receipts\_root|miner|difficulty|total\_difficulty|size|extra\_data|gas\_limit|gas\_used|timestamp|transaction\_count|base\_fee\_per\_gas|
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
|0|15537391|0x2f1dc309c7cc0a5a2e3b3dd9315fea0ffbc53c56f9237f3ca11b20de0232f153|0xd5b9efdd3659f5b635e0505d787d6b6cc3af4c660def9676188cda2bb026bffd|0xac2c3800025a764f|0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347|0x53a240c0610070015299420086041090205a1106210008400082344ac4142014222281180000001002893c01476030000a8481c92d142d00002000008a24281021504000002000bc6a0680081643112104010090090e265b3120540380000bc540600400c620108180042c5100cc08dc002a00904a51933160a81010444940f20000200423c83848130d8a0420c9c22240801a018108100a5222804b8d466b4b3a52014500a8a08424024c00241a80900a8041bc622db10209200022c04ca5000030000ec4110400248002300c40800148166384e7e80812920021018800e002007060c3004068125ac13058b160283604206948102888500600080058915c22|0xd976f002afbac9fdf1b028336719b602b9f4660ca103b8963b2f05a4f951cdc9|0xb8d426f8c8b6ae1c34f6bebf904971be1611c29e8889c7133bdef5e4e9e60b7f|0x6b4d994610806d8a5ed107996abc477688d4d0748763828f68c0d8df174ba256|0x829bd824b016326a401d083b33d092293333a830|11043900012338719|58749981610968571282265|47274|0xe4b883e5bda9e7a59ee4bb99e9b1bc4b2e22|30000000|16969164|1663224155|105|37949635702|
|1|15537392|0x2b3ea3cd4befcab070812443affb08bf17a91ce382c714a536ca3cacab82278b|0x2f1dc309c7cc0a5a2e3b3dd9315fea0ffbc53c56f9237f3ca11b20de0232f153|0x232b0043952c93d9|0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347|0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff|0x82864b3a65d1ac1917c426d48915dca0fc966fbf3f30fd051659f35dc3fd9be1|0xfee48a40a2765ab31fcd06ab6956341d13dc2c4b9762f2447aa425bb1c089b30|0x13c10513b52358022f800e2f9f1c50328798427b1b4a1ebbbd20b7417fb9719d|0xea674fdde714fd979de3edf0f56aa9716b898ec8|11049842297455506|58749992660810868737771|16568|0x617369612d65617374322d31763932|30000000|29990952|1663224156|61|38572377838|
|2|15537393|0x55b11b918355b1ef9c5db810302ebad0bf2544255b530cdce90674d5887bb286|0x2b3ea3cd4befcab070812443affb08bf17a91ce382c714a536ca3cacab82278b|0x62a3ee77461d4fc9|0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347|0x00000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000008000000000000000000000000000000000000000000000000020000000000000000000800000000004000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008400000000001002000000000000000000000000000000000002000000020000000020000000000000000000000000000000000000000040000000000000000000000000|0xdd5eec02b019ff76e359b09bfa19395a2a0e97bc01e70d8d5491e640167c96a8|0x4919dafa6ac8becfbbd0c2808f6c9511a057c21e42839caff5dfb6d3ef514951|0xbaa842cfd552321a9c2450576126311e071680a1258032219c6490b663c1dab8|0x829bd824b016326a401d083b33d092293333a830|11055787484078698|58750003716598352816469|1636|0xe4b883e5bda9e7a59ee4bb99e9b1bc460021|30000000|29991429|1663224162|1|43391016710|
|3|15537394|0x56a9bb0302da44b8c0b3df540781424684c3af04d0b7a38d72842b762076a664|0x55b11b918355b1ef9c5db810302ebad0bf2544255b530cdce90674d5887bb286|0x0000000000000000|0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347|0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff|0x1ea1746468686159ce730c1cc49a886721244e5d1fa9a06d6d4196b6f013c82c|0x40c07091e16263270f3579385090fea02dd5f061ba6750228fcc082ff762fda7|0x928073fb98ce316265ea35d95ab7e2e1206cecd85242eb841dbbcc4f568fca4b|0xeee27662c2b8eba3cd936a23f039f3189633e4c8|0|58750003716598352816469|18559|0x|30000000|29983006|1663224179|80|48811794595|
|4|15537395|0xe37e1a183a3d1c7234d090bfb7196081635919c26f2e65c67c106513158a7db4|0x56a9bb0302da44b8c0b3df540781424684c3af04d0b7a38d72842b762076a664|0x0000000000000000|0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347|0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff|0x5c56184fbce74e9c98d2a51aa2110963396047d84e8ce1ae1785337255cd11e0|0x2ca38a39c5517f658d107c19550334a9820a7393d14857f2c0e0458292668d64|0x1707e457973ce280debe93f5d478663d97ad192beea1f2fc65f391db80226e5e|0x0b3b161b8abeb6b04cb95c3e6047f80c120a0292|0|58750003716598352816469|36978|0x|30000000|29982083|1663224191|29|54906356355|

*Table 2. Copy of the output of datafram querying via Alchemy endpoint (15537391-15537395)* 

Comparing *Table 1* and *Table 2*, we can easily find that all the block data querying via Infura and Alchemy are the same. For example, if we check the block number, hash, and nonce of *Table 1* and *Table 2*, they are all the same.

## Question 2

Please introduce the token that you queried in 100 words:


*   when the token first was issued?
*   what functions do the token support?
*   what is the current market value of the token? 

Please provide references that could back-up your answer. 
Please insert Figures/Tables to better represent your idea.

**Token name: Uniswap**



[Uniswap token (UNI)](https://uniswap.org/blog/uni) was first issued on Sept. 17, 2020, by [Uniswap](https://uniswap.org/), a decentralized exchange that allows swaping various Ethereum-based ERC-20 tokens from a simple web interface ([Dalton 2020](https://cryptobriefing.com/what-is-uniswap-introduction-uni-token/)).
The UNI token is used in governance. UNI holders can influence and vote on Uniswap development decisions. They can also fund grants, partnerships, liquidity mining pools, and other proposals ([Dalton 2020](https://cryptobriefing.com/what-is-uniswap-introduction-uni-token/)).
The current market value of UNI token is USD5.70 ([“Uniswap Price | UNI Price, USD Converter, Charts | Crypto.com” 2022](https://crypto.com/price/uniswap)).

  ![UNI Price](https://raw.githubusercontent.com/Rising-Stars-by-Sunshine/Yutong-Quan/main/image/Uniswap%20Price.jpg)
  *Figure 1. UNI Market Price on Nov. 12, 2022 (17:37 EST)*

### Question 3: 

What are the changes of Ethereum before and after the merge? Please identify at least three different changes to elaborate on. 

Please provide references that could back-up your answer. 

Please insert Figures/Tables to better represent your idea.

The Merge of Ethereum leads to changes in consensus mechanism, ETH issuance, and energy expenditure.

*   **Consensus Mechanism:** *Figure 2* shows that the consensus mechanism of Ethereum changed from proof-of-work (PoW) to proof-of-stake (PoS) ([“The Merge” 2022](https://ethereum.org/en/upgrades/merge/#main-content)).

  ![Illustration of The Merge](https://raw.githubusercontent.com/Rising-Stars-by-Sunshine/Yutong-Quan/main/image/Illustration%20of%20The%20Merge.png)
  *Figure 2. Illustration of The Merge ([“The Merge” 2022](https://ethereum.org/en/upgrades/merge/#main-content))*

*   **ETH Issuance:** The issuance of ETH is the process of creating ETH that did not previously exist. Before the merge, miners were issued approximately 13,000 ETH/day, and stakers are issued approximately 1,700 ETH/day, for a total of 14,700 ETH/day. Since the merge, only the ~1,700 ETH/day remains, dropping total new ETH issuance by ~88% ([“How the Merge Impacted ETH Supply” 2022](https://ethereum.org/en/upgrades/merge/issuance/)). *Figure 3* provides a visual illustration of the change in daily block rewards before and after the merge.

  ![Ethereum Daily Block Rewards Chart](https://raw.githubusercontent.com/Rising-Stars-by-Sunshine/Yutong-Quan/main/image/ethereum-daily-block-rew.jpeg)
  *Figure 3. Ethereum Daily Block Rewards Chart ([Etherscan 2022](https://etherscan.io/chart/blockreward))*

*   **Energy Expenditure:** When it was using PoW consensus mechanism, the Ethereum network yielded an estimate of 78 TWh for the network’s annual electricity consumption. After the merge, the energy consumption of the Ethereum network using PoS model drops to 0.0026 TWh/yr ([“Ethereum Energy Consumption” 2022](https://ethereum.org/en/energy-consumption/)). The Merge reduced Ethereum's energy consumption by ~99.95% ([“The Merge” 2022](https://ethereum.org/en/upgrades/merge/#main-content)). *Figure 4* shows an interesting comparison of Ethereum's energy expenditure before and after the merge.

  ![Ethereum Energy Consumption Pre and Post The Merge](https://raw.githubusercontent.com/Rising-Stars-by-Sunshine/Yutong-Quan/main/image/energy_consumption_pre_post_merge.png)
  *Figure 4. Comparison of Energy Consumption of Ethereum "pre-Merge" and "post-Merge" ([“Ethereum Energy Consumption” 2022](https://ethereum.org/en/energy-consumption/))*

# Part I: Install Required Dependancies

In [ ]:
# install ethereum-etl and pandas
!python -m pip install ethereum-etl pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: ethereum-etl in /usr/local/lib/python3.7/dist-packages (2.1.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.3.5)
Requirement already satisfied: python-dateutil<3,>=2.8.0 in /usr/local/lib/python3.7/dist-packages (from ethereum-etl) (2.8.2)
Requirement already satisfied: click==8.0.4 in /usr/local/lib/python3.7/dist-packages (from ethereum-etl) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from ethereum-etl) (2.23.0)
Requirement already satisfied: eth-utils==1.10 in /usr/local/lib/python3.7/dist-packages (from ethereum-etl) (1.10.0)
Requirement already satisfied: base58 in /usr/local/lib/python3.7/dist-packages (from ethereum-etl) (2.1.1)
Requirement already satisfied: ethereum-dasm==0.1.4 in /usr/local/lib/python3.7/dist-packages (from ethereum-etl) (0.1.4)
Requirement already satisfied: web3<6,>=5.29 in /usr/local/lib/python3.7/dist-packages (from ethereum-etl) (5.31.1)
Requirement already satisfied: eth-abi==2.1.1 in /usr/local/lib/python3.7/dist-packages (from ethereum-etl) (2.1.1)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from click==8.0.4->ethereum-etl) (4.13.0)
Requirement already satisfied: eth-typing<3.0.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from eth-abi==2.1.1->ethereum-etl) (2.3.0)
Requirement already satisfied: parsimonious<0.9.0,>=0.8.0 in /usr/local/lib/python3.7/dist-packages (from eth-abi==2.1.1->ethereum-etl) (0.8.1)
Requirement already satisfied: cytoolz<1.0.0,>=0.10.1 in /usr/local/lib/python3.7/dist-packages (from eth-utils==1.10->ethereum-etl) (0.12.0)
Requirement already satisfied: eth-hash<0.4.0,>=0.3.1 in /usr/local/lib/python3.7/dist-packages (from eth-utils==1.10->ethereum-etl) (0.3.3)
Requirement already satisfied: tabulate in /usr/local/lib/python3.7/dist-packages (from ethereum-dasm==0.1.4->ethereum-etl) (0.8.10)
Requirement already satisfied: evmdasm in /usr/local/lib/python3.7/dist-packages (from ethereum-dasm==0.1.4->ethereum-etl) (0.1.10)
Requirement already satisfied: colorama in /usr/local/lib/python3.7/dist-packages (from ethereum-dasm==0.1.4->ethereum-etl) (0.4.6)
Requirement already satisfied: toolz>=0.8.0 in /usr/local/lib/python3.7/dist-packages (from cytoolz<1.0.0,>=0.10.1->eth-utils==1.10->ethereum-etl) (0.12.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from parsimonious<0.9.0,>=0.8.0->eth-abi==2.1.1->ethereum-etl) (1.15.0)
Requirement already satisfied: ipfshttpclient==0.8.0a2 in /usr/local/lib/python3.7/dist-packages (from web3<6,>=5.29->ethereum-etl) (0.8.0a2)
Requirement already satisfied: protobuf==3.19.5 in /usr/local/lib/python3.7/dist-packages (from web3<6,>=5.29->ethereum-etl) (3.19.5)
Requirement already satisfied: lru-dict<2.0.0,>=1.1.6 in /usr/local/lib/python3.7/dist-packages (from web3<6,>=5.29->ethereum-etl) (1.1.8)
Requirement already satisfied: hexbytes<1.0.0,>=0.1.0 in /usr/local/lib/python3.7/dist-packages (from web3<6,>=5.29->ethereum-etl) (0.3.0)
Requirement already satisfied: eth-rlp<0.3 in /usr/local/lib/python3.7/dist-packages (from web3<6,>=5.29->ethereum-etl) (0.2.1)
Requirement already satisfied: eth-account<0.6.0,>=0.5.9 in /usr/local/lib/python3.7/dist-packages (from web3<6,>=5.29->ethereum-etl) (0.5.9)
Requirement already satisfied: typing-extensions<5,>=3.7.4.1 in /usr/local/lib/python3.7/dist-packages (from web3<6,>=5.29->ethereum-etl) (4.1.1)
Requirement already satisfied: websockets<10,>=9.1 in /usr/local/lib/python3.7/dist-packages (from web3<6,>=5.29->ethereum-etl) (9.1)
Requirement already satisfied: jsonschema<5,>=3.2.0 in /usr/local/lib/python3.7/dist-packages (from web3<6,>=5.29->ethereum-etl) (4.3.3)
Requirement already satisfied: aiohttp<4,>=3.7.4.post0 in /usr/local/lib/python3.7/dist-packages (from web3<6,>=5.29->ethereum-etl) (3.8.3)
Requirement already satisfied: multiaddr>=0.0.7 in /usr/local/lib/python3.7/dist-packages (from ipfshttpclient==0.8.0a2->web3<6,>=5.29->ethereum-etl) (0.0.9)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp<4,>=3.7.4.post0->web3<6,>=5.29->ethereum-etl) (22.1.0)
Requirement already satisfied: asynctest==0.13.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp<4,>=3.7.4.post0->web3<6,>=5.29->ethereum-etl) (0.13.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.7/dist-packages (from aiohttp<4,>=3.7.4.post0->web3<6,>=5.29->ethereum-etl) (6.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp<4,>=3.7.4.post0->web3<6,>=5.29->ethereum-etl) (1.8.1)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.7/dist-packages (from aiohttp<4,>=3.7.4.post0->web3<6,>=5.29->ethereum-etl) (1.3.3)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.7/dist-packages (from aiohttp<4,>=3.7.4.post0->web3<6,>=5.29->ethereum-etl) (4.0.2)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.7/dist-packages (from aiohttp<4,>=3.7.4.post0->web3<6,>=5.29->ethereum-etl) (1.3.1)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp<4,>=3.7.4.post0->web3<6,>=5.29->ethereum-etl) (2.1.1)
Requirement already satisfied: bitarray<3,>=1.2.1 in /usr/local/lib/python3.7/dist-packages (from eth-account<0.6.0,>=0.5.9->web3<6,>=5.29->ethereum-etl) (2.6.0)
Requirement already satisfied: eth-keyfile<0.6.0,>=0.5.0 in /usr/local/lib/python3.7/dist-packages (from eth-account<0.6.0,>=0.5.9->web3<6,>=5.29->ethereum-etl) (0.5.1)
Requirement already satisfied: eth-keys<0.4.0,>=0.3.4 in /usr/local/lib/python3.7/dist-packages (from eth-account<0.6.0,>=0.5.9->web3<6,>=5.29->ethereum-etl) (0.3.4)
Requirement already satisfied: rlp<3,>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from eth-account<0.6.0,>=0.5.9->web3<6,>=5.29->ethereum-etl) (2.0.1)
Requirement already satisfied: pycryptodome<4,>=3.6.6 in /usr/local/lib/python3.7/dist-packages (from eth-hash<0.4.0,>=0.3.1->eth-utils==1.10->ethereum-etl) (3.15.0)
Requirement already satisfied: importlib-resources>=1.4.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema<5,>=3.2.0->web3<6,>=5.29->ethereum-etl) (5.10.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema<5,>=3.2.0->web3<6,>=5.29->ethereum-etl) (0.19.2)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.7/dist-packages (from importlib-resources>=1.4.0->jsonschema<5,>=3.2.0->web3<6,>=5.29->ethereum-etl) (3.10.0)
Requirement already satisfied: netaddr in /usr/local/lib/python3.7/dist-packages (from multiaddr>=0.0.7->ipfshttpclient==0.8.0a2->web3<6,>=5.29->ethereum-etl) (0.8.0)
Requirement already satisfied: varint in /usr/local/lib/python3.7/dist-packages (from multiaddr>=0.0.7->ipfshttpclient==0.8.0a2->web3<6,>=5.29->ethereum-etl) (1.0.2)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->ethereum-etl) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->ethereum-etl) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->ethereum-etl) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->ethereum-etl) (2022.9.24)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.21.6)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2022.6)

# Part II: Mount Google Drive for Result Exports

In [ ]:
# mount google drive
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# print the current directory
!pwd

/content/drive/My Drive/STATS201

In [ ]:
#@title path
#create a project folder and identify the path
path = "/content/drive/MyDrive/STATS201" #@param {type:"string"}

In [ ]:
#go to your project folder 
%cd /content/drive/MyDrive/STATS201

/content/drive/MyDrive/STATS201

In [ ]:
# print the current directory again to make sure that you are in the project folder
!pwd

/content/drive/MyDrive/STATS201

# Part III: Query Data and Export CSV

## 0.Register Accounts on Remote Nodes Service and Get the URLs of the Nodes

### Remote node option 1: Infura

!!! Important Notes: Please replace https://mainnet.infura.io/v3/API_KEY with your own endpoints for all the codes below

In [ ]:
#@title Import using the Infura node
infura_end_points_URL = "https://mainnet.infura.io/v3/API_KEY" #@param {type:"string"}

### Remote node option 2: Alchemy

In [ ]:
#@title import using Alchemy
alchemy_end_points_URL = "https://eth-mainnet.g.alchemy.com/v2/API_KEY" #@param {type:"string"}

### Remote node option 3: QuickNode

In [ ]:
#@title import using QuickNode
QuickNode_end_points_URL = "https://black-ancient-slug.discover.quiknode.pro/API_KEY" #@param {type:"string"}



Data Range: We are going to query the block and transaction data for the ethereum blockchain before and after the merge (block number: 15537393 on September 15)

Reference; 
https://www.investopedia.com/ethereum-completes-the-merge-6666337

In [ ]:
#@title the merge
merge = 15537393 #@param {type:"number"}

In [ ]:
#@title data radius
radius = 2 #@param {type:"number"}

In [ ]:
### find the start and the end
start = merge-radius
end = merge+radius
print(start, end)

15537391 15537395

## 1. Query Block Data

### using the infura endpoint

In [ ]:
!ethereumetl export_blocks_and_transactions --start-block 15537391 --end-block 15537395 --blocks-output blocks.csv --provider-uri https://mainnet.infura.io/v3/API_KEY

2022-11-16 08:27:58,104 - ProgressLogger [INFO] - Started work. Items to process: 5.
2022-11-16 08:27:58,283 - ProgressLogger [INFO] - 5 items processed. Progress is 100%.
2022-11-16 08:27:58,283 - ProgressLogger [INFO] - Finished work. Total items processed: 5. Took 0:00:00.179221.
2022-11-16 08:27:58,285 - CompositeItemExporter [INFO] - block items exported: 5
2022-11-16 08:27:58,285 - CompositeItemExporter [INFO] - transaction items exported: 0

In [ ]:
# import libraries to print data frame
import pandas as pd

In [ ]:
# set to print the maximum numbers of rows
pd.set_option('display.max_rows', None)

In [ ]:
df_blocks = pd.read_csv('./blocks.csv')
display(df_blocks.head())

,number,hash,parent_hash,nonce,sha3_uncles,logs_bloom,transactions_root,state_root,receipts_root,miner,difficulty,total_difficulty,size,extra_data,gas_limit,gas_used,timestamp,transaction_count,base_fee_per_gas
0,15537391,0x2f1dc309c7cc0a5a2e3b3dd9315fea0ffbc53c56f923...,0xd5b9efdd3659f5b635e0505d787d6b6cc3af4c660def...,0xac2c3800025a764f,0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a...,0x53a240c0610070015299420086041090205a11062100...,0xd976f002afbac9fdf1b028336719b602b9f4660ca103...,0xb8d426f8c8b6ae1c34f6bebf904971be1611c29e8889...,0x6b4d994610806d8a5ed107996abc477688d4d0748763...,0x829bd824b016326a401d083b33d092293333a830,11043900012338719,58749981610968571282265,47274,0xe4b883e5bda9e7a59ee4bb99e9b1bc4b2e22,30000000,16969164,1663224155,105,37949635702
1,15537392,0x2b3ea3cd4befcab070812443affb08bf17a91ce382c7...,0x2f1dc309c7cc0a5a2e3b3dd9315fea0ffbc53c56f923...,0x232b0043952c93d9,0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a...,0xffffffffffffffffffffffffffffffffffffffffffff...,0x82864b3a65d1ac1917c426d48915dca0fc966fbf3f30...,0xfee48a40a2765ab31fcd06ab6956341d13dc2c4b9762...,0x13c10513b52358022f800e2f9f1c50328798427b1b4a...,0xea674fdde714fd979de3edf0f56aa9716b898ec8,11049842297455506,58749992660810868737771,16568,0x617369612d65617374322d31763932,30000000,29990952,1663224156,61,38572377838
2,15537393,0x55b11b918355b1ef9c5db810302ebad0bf2544255b53...,0x2b3ea3cd4befcab070812443affb08bf17a91ce382c7...,0x62a3ee77461d4fc9,0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a...,0x00000400000000000000000000000000000000000000...,0xdd5eec02b019ff76e359b09bfa19395a2a0e97bc01e7...,0x4919dafa6ac8becfbbd0c2808f6c9511a057c21e4283...,0xbaa842cfd552321a9c2450576126311e071680a12580...,0x829bd824b016326a401d083b33d092293333a830,11055787484078698,58750003716598352816469,1636,0xe4b883e5bda9e7a59ee4bb99e9b1bc460021,30000000,29991429,1663224162,1,43391016710
3,15537394,0x56a9bb0302da44b8c0b3df540781424684c3af04d0b7...,0x55b11b918355b1ef9c5db810302ebad0bf2544255b53...,0x0000000000000000,0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a...,0xffffffffffffffffffffffffffffffffffffffffffff...,0x1ea1746468686159ce730c1cc49a886721244e5d1fa9...,0x40c07091e16263270f3579385090fea02dd5f061ba67...,0x928073fb98ce316265ea35d95ab7e2e1206cecd85242...,0xeee27662c2b8eba3cd936a23f039f3189633e4c8,0,58750003716598352816469,18559,0x,30000000,29983006,1663224179,80,48811794595
4,15537395,0xe37e1a183a3d1c7234d090bfb7196081635919c26f2e...,0x56a9bb0302da44b8c0b3df540781424684c3af04d0b7...,0x0000000000000000,0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a...,0xffffffffffffffffffffffffffffffffffffffffffff...,0x5c56184fbce74e9c98d2a51aa2110963396047d84e8c...,0x2ca38a39c5517f658d107c19550334a9820a7393d148...,0x1707e457973ce280debe93f5d478663d97ad192beea1...,0x0b3b161b8abeb6b04cb95c3e6047f80c120a0292,0,58750003716598352816469,36978,0x,30000000,29982083,1663224191,29,54906356355

### query blockchain data using the alchemy endpoint

In [ ]:
!ethereumetl export_blocks_and_transactions --start-block 15537391 --end-block 15537395 --blocks-output blocks_alchemy.csv --provider-uri https://eth-mainnet.g.alchemy.com/v2/API_KEY

2022-11-16 08:27:59,595 - ProgressLogger [INFO] - Started work. Items to process: 5.
2022-11-16 08:27:59,721 - ProgressLogger [INFO] - 5 items processed. Progress is 100%.
2022-11-16 08:27:59,721 - ProgressLogger [INFO] - Finished work. Total items processed: 5. Took 0:00:00.125537.
2022-11-16 08:27:59,723 - CompositeItemExporter [INFO] - block items exported: 5
2022-11-16 08:27:59,723 - CompositeItemExporter [INFO] - transaction items exported: 0

In [ ]:
df_blocks_alchemy = pd.read_csv('./blocks_alchemy.csv')
display(df_blocks_alchemy.head())

,number,hash,parent_hash,nonce,sha3_uncles,logs_bloom,transactions_root,state_root,receipts_root,miner,difficulty,total_difficulty,size,extra_data,gas_limit,gas_used,timestamp,transaction_count,base_fee_per_gas
0,15537391,0x2f1dc309c7cc0a5a2e3b3dd9315fea0ffbc53c56f923...,0xd5b9efdd3659f5b635e0505d787d6b6cc3af4c660def...,0xac2c3800025a764f,0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a...,0x53a240c0610070015299420086041090205a11062100...,0xd976f002afbac9fdf1b028336719b602b9f4660ca103...,0xb8d426f8c8b6ae1c34f6bebf904971be1611c29e8889...,0x6b4d994610806d8a5ed107996abc477688d4d0748763...,0x829bd824b016326a401d083b33d092293333a830,11043900012338719,58749981610968571282265,47274,0xe4b883e5bda9e7a59ee4bb99e9b1bc4b2e22,30000000,16969164,1663224155,105,37949635702
1,15537392,0x2b3ea3cd4befcab070812443affb08bf17a91ce382c7...,0x2f1dc309c7cc0a5a2e3b3dd9315fea0ffbc53c56f923...,0x232b0043952c93d9,0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a...,0xffffffffffffffffffffffffffffffffffffffffffff...,0x82864b3a65d1ac1917c426d48915dca0fc966fbf3f30...,0xfee48a40a2765ab31fcd06ab6956341d13dc2c4b9762...,0x13c10513b52358022f800e2f9f1c50328798427b1b4a...,0xea674fdde714fd979de3edf0f56aa9716b898ec8,11049842297455506,58749992660810868737771,16568,0x617369612d65617374322d31763932,30000000,29990952,1663224156,61,38572377838
2,15537393,0x55b11b918355b1ef9c5db810302ebad0bf2544255b53...,0x2b3ea3cd4befcab070812443affb08bf17a91ce382c7...,0x62a3ee77461d4fc9,0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a...,0x00000400000000000000000000000000000000000000...,0xdd5eec02b019ff76e359b09bfa19395a2a0e97bc01e7...,0x4919dafa6ac8becfbbd0c2808f6c9511a057c21e4283...,0xbaa842cfd552321a9c2450576126311e071680a12580...,0x829bd824b016326a401d083b33d092293333a830,11055787484078698,58750003716598352816469,1636,0xe4b883e5bda9e7a59ee4bb99e9b1bc460021,30000000,29991429,1663224162,1,43391016710
3,15537394,0x56a9bb0302da44b8c0b3df540781424684c3af04d0b7...,0x55b11b918355b1ef9c5db810302ebad0bf2544255b53...,0x0000000000000000,0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a...,0xffffffffffffffffffffffffffffffffffffffffffff...,0x1ea1746468686159ce730c1cc49a886721244e5d1fa9...,0x40c07091e16263270f3579385090fea02dd5f061ba67...,0x928073fb98ce316265ea35d95ab7e2e1206cecd85242...,0xeee27662c2b8eba3cd936a23f039f3189633e4c8,0,58750003716598352816469,18559,0x,30000000,29983006,1663224179,80,48811794595
4,15537395,0xe37e1a183a3d1c7234d090bfb7196081635919c26f2e...,0x56a9bb0302da44b8c0b3df540781424684c3af04d0b7...,0x0000000000000000,0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a...,0xffffffffffffffffffffffffffffffffffffffffffff...,0x5c56184fbce74e9c98d2a51aa2110963396047d84e8c...,0x2ca38a39c5517f658d107c19550334a9820a7393d148...,0x1707e457973ce280debe93f5d478663d97ad192beea1...,0x0b3b161b8abeb6b04cb95c3e6047f80c120a0292,0,58750003716598352816469,36978,0x,30000000,29982083,1663224191,29,54906356355

### query the data using the QuickNode endpoint

In [ ]:
!ethereumetl export_blocks_and_transactions --start-block 15537391 --end-block 15537395 --blocks-output blocks_QuickNode.csv --provider-uri https://black-ancient-slug.discover.quiknode.pro/API_KEY

2022-11-16 08:28:01,002 - ProgressLogger [INFO] - Started work. Items to process: 5.
2022-11-16 08:28:01,155 - ProgressLogger [INFO] - 5 items processed. Progress is 100%.
2022-11-16 08:28:01,156 - ProgressLogger [INFO] - Finished work. Total items processed: 5. Took 0:00:00.153661.
2022-11-16 08:28:01,157 - CompositeItemExporter [INFO] - block items exported: 5
2022-11-16 08:28:01,157 - CompositeItemExporter [INFO] - transaction items exported: 0

In [ ]:
df_blocks_QuickNode = pd.read_csv('./blocks_QuickNode.csv')
display(df_blocks_QuickNode.head(10))

,number,hash,parent_hash,nonce,sha3_uncles,logs_bloom,transactions_root,state_root,receipts_root,miner,difficulty,total_difficulty,size,extra_data,gas_limit,gas_used,timestamp,transaction_count,base_fee_per_gas
0,15537391,0x2f1dc309c7cc0a5a2e3b3dd9315fea0ffbc53c56f923...,0xd5b9efdd3659f5b635e0505d787d6b6cc3af4c660def...,0xac2c3800025a764f,0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a...,0x53a240c0610070015299420086041090205a11062100...,0xd976f002afbac9fdf1b028336719b602b9f4660ca103...,0xb8d426f8c8b6ae1c34f6bebf904971be1611c29e8889...,0x6b4d994610806d8a5ed107996abc477688d4d0748763...,0x829bd824b016326a401d083b33d092293333a830,11043900012338719,58749981610968571282265,47274,0xe4b883e5bda9e7a59ee4bb99e9b1bc4b2e22,30000000,16969164,1663224155,105,37949635702
1,15537392,0x2b3ea3cd4befcab070812443affb08bf17a91ce382c7...,0x2f1dc309c7cc0a5a2e3b3dd9315fea0ffbc53c56f923...,0x232b0043952c93d9,0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a...,0xffffffffffffffffffffffffffffffffffffffffffff...,0x82864b3a65d1ac1917c426d48915dca0fc966fbf3f30...,0xfee48a40a2765ab31fcd06ab6956341d13dc2c4b9762...,0x13c10513b52358022f800e2f9f1c50328798427b1b4a...,0xea674fdde714fd979de3edf0f56aa9716b898ec8,11049842297455506,58749992660810868737771,16568,0x617369612d65617374322d31763932,30000000,29990952,1663224156,61,38572377838
2,15537393,0x55b11b918355b1ef9c5db810302ebad0bf2544255b53...,0x2b3ea3cd4befcab070812443affb08bf17a91ce382c7...,0x62a3ee77461d4fc9,0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a...,0x00000400000000000000000000000000000000000000...,0xdd5eec02b019ff76e359b09bfa19395a2a0e97bc01e7...,0x4919dafa6ac8becfbbd0c2808f6c9511a057c21e4283...,0xbaa842cfd552321a9c2450576126311e071680a12580...,0x829bd824b016326a401d083b33d092293333a830,11055787484078698,58750003716598352816469,1636,0xe4b883e5bda9e7a59ee4bb99e9b1bc460021,30000000,29991429,1663224162,1,43391016710
3,15537394,0x56a9bb0302da44b8c0b3df540781424684c3af04d0b7...,0x55b11b918355b1ef9c5db810302ebad0bf2544255b53...,0x0000000000000000,0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a...,0xffffffffffffffffffffffffffffffffffffffffffff...,0x1ea1746468686159ce730c1cc49a886721244e5d1fa9...,0x40c07091e16263270f3579385090fea02dd5f061ba67...,0x928073fb98ce316265ea35d95ab7e2e1206cecd85242...,0xeee27662c2b8eba3cd936a23f039f3189633e4c8,0,58750003716598352816469,18559,0x,30000000,29983006,1663224179,80,48811794595
4,15537395,0xe37e1a183a3d1c7234d090bfb7196081635919c26f2e...,0x56a9bb0302da44b8c0b3df540781424684c3af04d0b7...,0x0000000000000000,0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a...,0xffffffffffffffffffffffffffffffffffffffffffff...,0x5c56184fbce74e9c98d2a51aa2110963396047d84e8c...,0x2ca38a39c5517f658d107c19550334a9820a7393d148...,0x1707e457973ce280debe93f5d478663d97ad192beea1...,0x0b3b161b8abeb6b04cb95c3e6047f80c120a0292,0,58750003716598352816469,36978,0x,30000000,29982083,1663224191,29,54906356355

## 2. Query Transaction Data

In [ ]:
!ethereumetl export_blocks_and_transactions --start-block 15537391 --end-block 15537395 --transactions-output transactions.csv --provider-uri https://mainnet.infura.io/v3/API_KEY

2022-11-16 08:28:03,828 - ProgressLogger [INFO] - Started work. Items to process: 5.
2022-11-16 08:28:04,286 - ProgressLogger [INFO] - 5 items processed. Progress is 100%.
2022-11-16 08:28:04,287 - ProgressLogger [INFO] - Finished work. Total items processed: 5. Took 0:00:00.458940.
2022-11-16 08:28:04,287 - CompositeItemExporter [INFO] - block items exported: 0
2022-11-16 08:28:04,297 - CompositeItemExporter [INFO] - transaction items exported: 276

In [ ]:
df_transactions = pd.read_csv('./transactions.csv')
display(df_transactions.head())

,hash,nonce,block_hash,block_number,transaction_index,from_address,to_address,value,gas,gas_price,input,block_timestamp,max_fee_per_gas,max_priority_fee_per_gas,transaction_type
0,0x7d354eee5c08004aa1b8a3a05e1cf9cd348ee88be456...,0,0x2f1dc309c7cc0a5a2e3b3dd9315fea0ffbc53c56f923...,15537391,0,0xb578405df1f9d4dfdd46a0bd152d518d4c5fe0ac,0xc86e1a7a4aa5a9b17f6997a59b311835fc95e975,0,169420,69420314159,0x7fec8d38,1663224155,6.942031e+10,6.942031e+10,2
1,0x105acb5c3118b319e0bd2a50e1e1f5c71f2761337efc...,106,0x2f1dc309c7cc0a5a2e3b3dd9315fea0ffbc53c56f923...,15537391,1,0x122b96a341ab8da83eb86f4dcefaa4b1d43125e9,0x7bc25283a29a3888cab4555ea86ff1a8c18cc90a,0,180000,69000000000,0x1249c58b,1663224155,6.900000e+10,6.900000e+10,2
2,0x2c6d2799f6a4d958264297a10a0782c1eec6cd6f22dc...,72,0x2f1dc309c7cc0a5a2e3b3dd9315fea0ffbc53c56f923...,15537391,2,0xdf0e3867920d812b74d05b19da043679f1082512,0x7bc25283a29a3888cab4555ea86ff1a8c18cc90a,0,180000,57949635702,0x1249c58b,1663224155,7.000000e+10,2.000000e+10,2
3,0xebbbf696a61de0d588aad04b55208e94edd71689f83f...,1366,0x2f1dc309c7cc0a5a2e3b3dd9315fea0ffbc53c56f923...,15537391,3,0x23bc95f84bd43c1fcc2bc285fda4cb12f9aee2df,0x23bc95f84bd43c1fcc2bc285fda4cb12f9aee2df,0,37428,57949635702,0x6d657267652063756d2063756d206161616161206d65...,1663224155,2.000000e+11,2.000000e+10,2
4,0xf8bc06020fc243959c8ef4be0b303370567af38be17a...,30,0x2f1dc309c7cc0a5a2e3b3dd9315fea0ffbc53c56f923...,15537391,4,0xeefd3779a860234ba029c618bab331f4f19afce3,0xdb7a53e6ae058e1dcf4502341e2adfa522e2b29f,0,384417,44493182647,0x00edfe033dfea8d90085171b721db6c000032313035b...,1663224155,NaN,NaN,0

## 3. Query Token Data

### 3.1 Query All Token Transfers

In [ ]:
!ethereumetl export_token_transfers --start-block 15537391 --end-block 15537395 --provider-uri https://eth-mainnet.g.alchemy.com/v2/API_KEY --output token_transfers.csv

2022-11-16 08:28:07,823 - ProgressLogger [INFO] - Started work. Items to process: 5.
2022-11-16 08:28:19,569 - ProgressLogger [INFO] - 5 items processed. Progress is 100%.
2022-11-16 08:28:19,570 - ProgressLogger [INFO] - Finished work. Total items processed: 5. Took 0:00:11.747014.
2022-11-16 08:28:19,571 - CompositeItemExporter [INFO] - token_transfer items exported: 30190

In [ ]:
df_token_transfers = pd.read_csv('./token_transfers.csv')
display(df_token_transfers.head())

,token_address,from_address,to_address,value,transaction_hash,log_index,block_number
0,0x7bc25283a29a3888cab4555ea86ff1a8c18cc90a,0x0000000000000000000000000000000000000000,0x122b96a341ab8da83eb86f4dcefaa4b1d43125e9,6366,0x105acb5c3118b319e0bd2a50e1e1f5c71f2761337efc...,0,15537391
1,0x7bc25283a29a3888cab4555ea86ff1a8c18cc90a,0x0000000000000000000000000000000000000000,0xdf0e3867920d812b74d05b19da043679f1082512,6367,0x2c6d2799f6a4d958264297a10a0782c1eec6cd6f22dc...,1,15537391
2,0x7bc25283a29a3888cab4555ea86ff1a8c18cc90a,0x0000000000000000000000000000000000000000,0xd8533d518b4a70d8f8a591ca34797d3cce5e1aff,6368,0xf6e28767052a31f93189da0774c4d605964f0f2c0e51...,3,15537391
3,0x7bc25283a29a3888cab4555ea86ff1a8c18cc90a,0x0000000000000000000000000000000000000000,0x35c99b7e6dc92eb10884e87fb99862ce7efb8f67,6369,0x12974832ad7c121d9cbc26e16f19c8e3bcfe703fa17f...,4,15537391
4,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640,0xb9ef128ac6c5961f3cb9baca36c4ac03f9d2cccd,399209476,0xdc2e70a469c1fc6c9efb4d783d148349d705ea543696...,5,15537391

In [ ]:
df = df_token_transfers[df_token_transfers.token_address=="0x7bc25283a29a3888cab4555ea86ff1a8c18cc90a"]
df.head()

,token_address,from_address,to_address,value,transaction_hash,log_index,block_number
0,0x7bc25283a29a3888cab4555ea86ff1a8c18cc90a,0x0000000000000000000000000000000000000000,0x122b96a341ab8da83eb86f4dcefaa4b1d43125e9,6366,0x105acb5c3118b319e0bd2a50e1e1f5c71f2761337efc...,0,15537391
1,0x7bc25283a29a3888cab4555ea86ff1a8c18cc90a,0x0000000000000000000000000000000000000000,0xdf0e3867920d812b74d05b19da043679f1082512,6367,0x2c6d2799f6a4d958264297a10a0782c1eec6cd6f22dc...,1,15537391
2,0x7bc25283a29a3888cab4555ea86ff1a8c18cc90a,0x0000000000000000000000000000000000000000,0xd8533d518b4a70d8f8a591ca34797d3cce5e1aff,6368,0xf6e28767052a31f93189da0774c4d605964f0f2c0e51...,3,15537391
3,0x7bc25283a29a3888cab4555ea86ff1a8c18cc90a,0x0000000000000000000000000000000000000000,0x35c99b7e6dc92eb10884e87fb99862ce7efb8f67,6369,0x12974832ad7c121d9cbc26e16f19c8e3bcfe703fa17f...,4,15537391
6,0x7bc25283a29a3888cab4555ea86ff1a8c18cc90a,0x0000000000000000000000000000000000000000,0x30d167662ceffb8708fc82e375d0785df78d02ba,6370,0x452d52918c88e3dcdff2b390e6c5faa16d89b701e555...,11,15537391

### 3.1 Query a specific token transfers

*references*:

* Commond Documentations: https://ethereum-etl.readthedocs.io/en/latest/commands/
* Token Address: https://github.com/blockchain-etl/ethereum-etl-airflow/blob/master/dags/resources/stages/seed/data/token_amendments.csv
* More detailed: https://github.com/blockchain-etl/ethereum-etl-airflow
* Proof-of-Reserve: https://blog.chain.link/stablecoins-and-proof-of-reserve/

In [ ]:
#@title Token Name
Token_Name = "Uniswap" #@param {type:"string"}

In [ ]:
#@title Token Symbol
Token_Symbol = "UNI" #@param {type:"string"}

In [ ]:
#@title Token Address
token_address = "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984" #@param {type:"string"}

Since the original range of 15537391-15537395 (radius = 2) returns empty result for this token, the range is changed to 15537388-15537398 (radius = 5) here.

In [ ]:
!ethereumetl export_token_transfers --start-block 15537388 --end-block 15537398 --provider-uri https://eth-mainnet.g.alchemy.com/v2/API_KEY --output token_transfers_UNI.csv --tokens 0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984

2022-11-16 08:28:20,742 - ProgressLogger [INFO] - Started work. Items to process: 11.
2022-11-16 08:28:21,019 - ProgressLogger [INFO] - 11 items processed. Progress is 100%.
2022-11-16 08:28:21,019 - ProgressLogger [INFO] - Finished work. Total items processed: 11. Took 0:00:00.277011.
2022-11-16 08:28:21,021 - CompositeItemExporter [INFO] - token_transfer items exported: 3

In [ ]:
df_token_transfers_UNI = pd.read_csv('./token_transfers_UNI.csv')
display(df_token_transfers_UNI.head())

,token_address,from_address,to_address,value,transaction_hash,log_index,block_number
0,0x1f9840a85d5af5bf1d1762f925bdaddc4201f984,0xdafd66636e2561b0284edde37e42d192f2844d40,0x74de5d4fcbf63e00296fd95d33236b9794016631,5974796181176103987,0x7eed50059bb7f850de7221bd9959522461edef5cd702...,60,15537388
1,0x1f9840a85d5af5bf1d1762f925bdaddc4201f984,0x74de5d4fcbf63e00296fd95d33236b9794016631,0x2acf35c9a3f4c5c3f4c78ef5fb64c3ee82f07c45,52279466585290908,0x7eed50059bb7f850de7221bd9959522461edef5cd702...,63,15537388
2,0x1f9840a85d5af5bf1d1762f925bdaddc4201f984,0x74de5d4fcbf63e00296fd95d33236b9794016631,0x8e2efa9ed16f07d9b153d295d35025fd677bae99,5922516714590813079,0x7eed50059bb7f850de7221bd9959522461edef5cd702...,64,15537388